[package]
name = "tlm_webui"
version = "0.1.0"
edition = "2018"
description = "Yew WebUI for TLM"
readme = "README.md"
keywords = ["yew", "trunk"]
categories = ["gui", "wasm", "web-programming"]

[dependencies]
yew = { version = "0.18", features = ["web_sys"]}
wasm-bindgen = "0.2.78"